source 'https://github.com/CocoaPods/Specs.git'

target 'STNotificationHelper', :exclusive => true do
  pod "STNotificationHelper", :path => "../STNotificationHelper.podspec"
end

target 'Tests', :exclusive => true do
  pod "STNotificationHelper", :path => "../STNotificationHelper.podspec"

  
end
